# Generated by Django 3.2.9 on 2021-12-11 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_alter_driver_created_at'),
        ('vehicle', '0004_alter_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 15, 22, 1, 411280)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
    ]
